server:
  port: 8483
  management-port: 8484
  context-path: /spark-scheduler
fifo: true
logging:
  level: info
  output: STDOUT
webhook-service-config:
  namespace: spark
  service-name: schedler-service
  service-port: 443
