apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: spark
spec:
  selector:
    app: spark-scheduler
    namespace: spark
    container: spark-scheduler-extender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8483